# .streamlit/config.toml

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
address = "localhost"  # Changed from 0.0.0.0

[browser]
serverAddress = "localhost"  # Changed from 0.0.0.0
gatherUsageStats = false

[theme]
primaryColor = "#0077BD"
backgroundColor = "#00263E"
secondaryBackgroundColor = "#005587"
textColor = "#FFFFFF"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"